# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
RegressionDisagreementDiversityMeasure
"""


from ..utils.entrypoints import Component


def regression_disagreement_diversity_measure(
        **params):
    """
    **Description**
        None

    """

    entrypoint_name = 'RegressionDisagreementDiversityMeasure'
    settings = {}

    return Component(
        name=entrypoint_name,
        settings=settings,
        kind='EnsembleRegressionDiversityMeasure',
    )
