# - Generated by tools/entrypoint_compiler.py: do not edit by hand
"""
SquaredLoss
"""


from ..utils.entrypoints import Component


def squared_loss(
        **params):
    """
    **Description**
        Squared loss.

    """

    entrypoint_name = 'SquaredLoss'
    settings = {}

    return Component(
        name=entrypoint_name,
        settings=settings,
        kind='SDCARegressionLossFunction',
    )
